### ISSUE TITLE
Settings in GAMEPLAY menu don't save

### ISSUE THREAD

**Issue by DamageMaximo** [Hibiscus14/ESCapism#2]
Everytime it resets to default when this mod is enabled

**Comment by Hibiscus14** [comment]
I found one problem when you use Risk Of Options, and im working on a fix
The problem is that when you enable the mod during the game and press ESCAPE the settings dont change, but if you manually press the correct button it works fine
I didnt find any other problems with other settings reseting on their own, so if the problem above isnt what you have been experiencing - please elaborate on what happened

**Comment by Hibiscus14** [comment]
It seems I managed to solve this problem in the current update, thanks!

**Comment by DamageMaximo** [comment]
Yup, it is fixed, thanks!
